services:
  server:
    environment:
      DB_HOST: bia-eb.cx4q6caas2ti.us-east-1.rds.amazonaws.com
      DB_PORT: "5432"
      DB_REGION: us-east-1
      DB_SECRET_NAME: rds!db-c71297df-52c2-4aa9-b107-a361a768a952
      DB_USER: postgres
    image: 194722426008.dkr.ecr.us-east-1.amazonaws.com/bia-eb:fda0a6c
    ports:
      - mode: ingress
        target: 8080
        published: "80"
        protocol: tcp
